// Additional scope explanations stay server rendered; they add no browser JS.
export const serviceContent = {
  'google-ads': {
    sections: [
      { heading: 'Google Ads Management Services in Ahmedabad', paragraphs: ['Our PPC management work starts with the services you want to sell, the areas you serve and the enquiries your team can handle. Search Ads reach people expressing a need; a campaign audit helps decide what to retain in an existing account.'], items: ['Campaign setup: group related searches, write ads that match the offer and agree geographic targeting.', 'Keyword research: separate buying intent from research, review search terms and exclude irrelevant searches.', 'Conversion tracking: test the enquiry or purchase journey before using its events to guide bidding.', 'Campaign optimization: review costs, negative keywords, ad messages and landing-page relevance alongside lead quality.'] },
      { heading: 'A practical Google Ads audit', paragraphs: ['Before changing an active account, we review conversion definitions, duplicate events, campaign settings, search terms, budget allocation and destination pages. You receive a prioritized plan explaining the problem, proposed action and how it will be checked.', 'Display and remarketing are considered only when the offer, available audience, consent and agreed scope support them. Search campaigns do not need every available ad format to be useful.'] },
      { heading: 'Why businesses work with InfronixWeb', paragraphs: ['Campaigns, website improvements and lead follow-up can be scoped together. That makes it easier to address a form problem or unclear landing page when it affects paid traffic. Reports distinguish clicks from enquiries and qualified sales opportunities; management fees and advertising spend remain separate.'], links: [['/digital-marketing', 'Coordinate your wider marketing plan'], ['/web-development', 'Review your campaign landing pages']] },
    ],
    guides: [['/blog/google-ads-management-guide', 'How to evaluate Google Ads management']],
  },
  seo: {
    sections: [
      { heading: 'Technical SEO Services in Ahmedabad', paragraphs: ['Technical SEO helps search engines access, render and understand the pages customers need. We use Search Console evidence and a crawl of the existing site to prioritize faults before changing working URLs or templates.'], items: ['Crawling and indexing: review robots directives, XML sitemaps, index coverage and the rendered content of important pages.', 'URL consistency: check canonicals, redirects, query parameters and duplicate content; preserve valuable indexed URLs.', 'Structured data: describe visible services, business information and articles without invented ratings or claims.', 'Performance and mobile SEO: investigate Core Web Vitals, large images, font loading, layout shifts and heavy JavaScript.', 'Internal linking: connect service pages and useful articles, repair broken destinations and check genuine 404 handling.'], links: [['/blog/technical-seo', 'Read the technical SEO checklist']] },
      { heading: 'SEO strategy, content and local discovery', paragraphs: ['Search Console queries help identify pages already receiving relevant impressions. We map a distinct intent to each page, then review titles, headings, useful answers and contextual links. Content optimization improves clarity and completeness rather than adding repeated keywords.', 'For local SEO, we review genuine business details and eligible Google Business Profile information. Service areas should reflect where the business actually works. We do not create fake locations, reviews or a separate page for every neighbourhood.'], links: [['/blog/seo-company-in-ahmedabad', 'Plan local search improvements'], ['/blog/ai-seo-generative-search', 'Understand AI SEO and generative search']] },
      { heading: 'SEO packages and engagement models', paragraphs: ['Choose an engagement around the work your site needs. There is no universal package or fixed price on this page: the proposal states deliverables, access, review milestones and responsibilities.'], items: ['Audit and implementation plan: diagnose technical and content gaps, prioritize fixes and agree who will implement them.', 'Ongoing SEO support: review Search Console, improve existing pages, maintain technical health and report relevant organic enquiries.', 'Technical or content project: scope a migration, indexing issue, internal-linking improvement or a useful topic cluster as a defined piece of work.'], links: [['/blog/seo-packages-guide', 'What to look for in an SEO package'], ['/start-project?service=seo', 'Request a scoped SEO quote']] },
    ],
  },
  'web-development': {
    sections: [
      { heading: 'Development, performance and handover', paragraphs: ['A business website needs clear navigation, accessible content and dependable enquiry forms. For ecommerce or a custom application, we first agree catalogue, checkout, permissions and integration requirements. Responsive layouts are checked across mobile and desktop screens.', 'We choose technology around the project rather than a fixed stack for every client. This site uses Next.js and React; API and database integrations are evaluated against access, maintenance and security requirements. Image sizing, font loading and server rendering are reviewed alongside the visual experience.'], items: ['Deliverables are agreed before development: page designs, content responsibilities, features and integration boundaries.', 'Before launch, check forms, key user journeys, metadata, redirects and loading behaviour.', 'Handover defines hosting, account ownership, maintenance and future update responsibilities.'], links: [['/projects', 'See the projects in our portfolio'], ['/blog/web-development-in-ahmedabad', 'Plan a website brief before choosing a developer'], ['/seo', 'Build search visibility into your website']] },
    ],
  },
  'ai-automation': {
    sections: [
      { heading: 'Connect lead, support and sales workflows', paragraphs: ['Start with one repeated business process: collecting enquiries, assigning follow-ups, answering approved support questions or keeping CRM records current. Map the inputs, exceptions and owner before deciding whether AI is needed.', 'Customer support and sales automation should preserve a clear human handoff. We scope permissions, review steps, failure alerts and handover documentation around your existing systems.'], links: [['/ai-chatbot', 'Explore assistants for customer questions'], ['/whatsapp-automation', 'Plan WhatsApp follow-ups and reminders'], ['/crm-automation', 'Connect CRM records and sales follow-up']] },
      { heading: 'AI automation and AI search serve different needs', paragraphs: ['Automation helps your team complete workflows. AI search optimization concerns whether your public content can be found and understood. If search visibility is your goal, start with accessible pages and useful information rather than a chatbot installation.'], links: [['/blog/ai-seo-generative-search', 'Read our guide to AI SEO'], ['/seo', 'Explore organic search support']] },
    ],
  },
  'digital-marketing': {
    sections: [{ heading: 'Match paid search to a clear offer', paragraphs: ['When customers already search for a service, a focused Google Search campaign can complement the wider content plan. Agree the landing page, enquiry definition and follow-up process before paying for traffic.'], links: [['/google-ads', 'Explore Google Ads campaign management'], ['/blog/google-ads-management-guide', 'Plan a search advertising budget']] }],
  },
};
