// One source for service discovery, useful scope details and related links.
export const services = [
  {
    slug: 'web-development', pillar: 'Build', name: 'Website Development',
    title: 'Web Development Company in Ahmedabad',
    description: 'Business websites, e-commerce stores, landing pages and custom business tools from InfronixWeb in Ahmedabad. Plan a new website or a careful redesign.',
    heading: 'Web Development Company in Ahmedabad',
    intro: 'A useful website makes your offer easy to understand and the next step easy to take. We plan, design and develop responsive websites for businesses in Ahmedabad and beyond.',
    includes: ['Business and corporate websites with clear service navigation', 'E-commerce catalogues, product pages and checkout integrations', 'Campaign landing pages and enquiry forms', 'Customer portals and connections to your business tools', 'Website redesign with URL and content migration planning', 'Mobile checks, fast-loading images and search-friendly pages'],
    problems: 'Unclear navigation, slow pages and hard-to-use mobile forms can prevent interested visitors from getting in touch. We identify those gaps before deciding what to rebuild or retain.',
    fit: 'Suitable for businesses launching their first site, replacing an outdated site, selling products online or bringing a manual task online.',
    process: ['Map your audience, content, existing URLs and required integrations.', 'Agree page structure and designs before development.', 'Build and check mobile layouts, accessibility, forms and loading behavior.', 'Review together, launch with redirects where needed, and agree maintenance responsibilities.'],
    example: 'Illustrative scope: a service business could replace a single crowded page with clear service pages, a project gallery and an enquiry form that records the selected service.',
    measure: 'Review enquiries, form completion, page speed and the paths visitors take. Maintenance, hosting and future content updates are scoped separately in the proposal.',
    faqs: [['Can you improve our current website?', 'Yes. We first review what works, then propose targeted changes or a redesign where the existing system limits your goals.'], ['Will existing search traffic be protected?', 'We record important pages and content, keep useful links working and check that Google can find the right pages after the change. Rankings cannot be guaranteed.'], ['What affects cost and timing?', 'Page count, supplied content, design requirements, e-commerce features and integrations determine the scope. A written proposal follows discovery.']],
    related: ['seo', 'digital-marketing', 'crm-automation'], proof: true,
  },
  {
    slug: 'seo', pillar: 'Grow', name: 'SEO', title: 'SEO Services in Ahmedabad | Website & Local Search',
    description: 'Website health checks, local search, customer keyword research and useful content for Ahmedabad businesses. Start with an audit and a measurable improvement plan.',
    heading: 'SEO Services in Ahmedabad',
    intro: 'Help people find useful answers and relevant services through organic search. Our SEO work connects website fixes, page content and local business information to your actual customer needs.',
    includes: ['Search visibility review with a clear list of improvements', 'Research into what customers search for and which pages answer them', 'Titles, headings, content improvements and internal linking', 'Checks that Google can find your pages and visitors can use them easily', 'Google Business Profile review and consistent local information', 'Genuine opportunities to promote your business and reporting on search enquiries'],
    problems: 'Google may struggle to find your pages, several pages may answer the same question, or your website may leave out information a customer needs. We diagnose the cause instead of repeating keywords across every page.',
    fit: 'Suitable for local service businesses, growing business websites and stores with existing pages that need better search visibility.',
    process: ['Review Search Console, analytics, the site and local profiles with permission.', 'Match customer questions to existing pages and identify missing answers.', 'Implement website fixes and useful content improvements.', 'Review which pages appear on Google, what people search for and the enquiries you receive.'],
    example: 'Illustrative scope: an Ahmedabad service business could improve its service-area information, connect relevant advice articles to service pages and correct inconsistent Business Profile details.',
    measure: 'Track non-branded organic clicks, relevant landing pages, qualified enquiries and local-profile actions. Search results depend on competition, site history and implementation; no ranking is guaranteed.',
    faqs: [['How soon will SEO show results?', 'Website fixes may be discovered quickly, but meaningful organic growth often takes sustained work. We agree review milestones without promising a ranking date.'], ['Do you manage Google Business Profile?', 'We can review categories, services, business information and content for a real eligible profile with owner access. We do not create fake locations or reviews.'], ['Do we need new articles?', 'Only where a useful question is not already answered. Existing pages are improved first, and each proposed article has a distinct purpose.']],
    related: ['web-development', 'digital-marketing', 'google-ads'],
  },
  {
    slug: 'digital-marketing', pillar: 'Grow', name: 'Digital Marketing', title: 'Digital Marketing Agency in Ahmedabad',
    description: 'Plan organic content, social media and paid advertising with InfronixWeb in Ahmedabad. Connect campaigns, landing pages and lead follow-up to business goals.',
    heading: 'Digital Marketing Strategies Built to Reach and Convert More Customers',
    intro: 'Bring your website, content, social channels and advertising into one practical plan. We help businesses choose the channels that fit their customers, offer and available budget.',
    includes: ['Audience research, positioning and channel strategy', 'Content planning for organic search and social media', 'Google Ads and Meta Ads campaign planning', 'Landing-page and enquiry-journey recommendations', 'Lead capture, follow-up coordination and funnel review', 'Reporting, experiments and ongoing optimization'],
    problems: 'Posting without a clear offer or running ads to an unclear landing page makes it difficult to learn what works. A shared strategy connects customer acquisition with the sales process.',
    fit: 'Suitable for businesses starting structured marketing, coordinating disconnected suppliers or reviewing which channels deserve investment.',
    process: ['Define your audience, offer and a meaningful conversion.', 'Separate organic content work from paid-media budgets and management.', 'Prepare content, landing pages and measurement before launch.', 'Review channel results and lead quality, then prioritize the next experiment.'],
    example: 'Illustrative scope: an enquiry-led business could combine useful search content with a focused search campaign and a consistent follow-up process for incoming leads.',
    measure: 'Organic marketing builds visibility through useful content over time. Paid advertising buys placements and needs a separate media budget. Reports distinguish reach and engagement from qualified enquiries and sales.',
    faqs: [['Should we start with organic marketing or ads?', 'That depends on demand, budget, timeline and the strength of your offer. We assess those factors before recommending a channel mix.'], ['Is advertising spend included?', 'Media spend and agency work should be listed separately in your proposal so you can see where the budget goes.'], ['Can you work with our sales team?', 'Yes. Agreeing what counts as a qualified lead and feeding sales outcomes back into reporting makes optimization more useful.']],
    related: ['seo', 'digital-marketing/social-media-marketing', 'google-ads', 'meta-ads', 'performance-marketing'],
  },
  {
    slug: 'ai-automation', pillar: 'Automate', name: 'AI Automation', title: 'AI Automation Agency in Ahmedabad',
    description: 'Practical AI and workflow automation for Ahmedabad businesses: lead capture, chatbots, WhatsApp, CRM, email and operations integrations scoped to your tools.',
    heading: 'AI Automation Agency in Ahmedabad',
    intro: 'Reduce repetitive work while keeping people responsible for important decisions. We map your workflow, check integration feasibility and build automations around the tools your team uses.',
    includes: ['Automatic lead capture and qualification workflows', 'Customer-support chatbots with human handoff', 'WhatsApp enquiries and appointment reminders', 'CRM updates, sales follow-ups and email automation', 'Document and data-processing workflows with review steps', 'Integration testing, failure alerts and handover documentation'],
    problems: 'Copying enquiries between tools, missing follow-ups and repeatedly answering the same questions take time away from customers. Start with a specific workflow and a clear owner.',
    fit: 'Suitable for teams with repeated tasks, accessible business data and someone responsible for reviewing exceptions. AI is optional; simple rules are often enough.',
    process: ['Document the current steps, volume, exceptions and data access.', 'Check which connections your tools support, the access needed, information quality and usage limits.', 'Pilot one workflow with test data and human review.', 'Test failures, train the team and agree monitoring and support.'],
    example: 'Illustrative scope: a website enquiry could be checked for required details, added to the CRM and assigned to a salesperson, with a reminder if nobody follows up.',
    measure: 'Compare manual steps, response time, exception rates and data accuracy before and after a pilot. Feasibility depends on requirements, integrations, supported tool connections, permissions and existing software.',
    faqs: [['Can automation replace our whole team?', 'No such promise is appropriate. Automation can assist defined tasks, while people handle judgment, exceptions and customer relationships.'], ['Can you connect our existing tools?', 'We first check supported connections, access permissions, subscription limits and data quality. Unsupported connections may require a different scope.'], ['How is sensitive data handled?', 'We agree which data is needed, who can access it, retention rules and which external providers receive it before implementation.']],
    related: ['ai-chatbot', 'whatsapp-automation', 'crm-automation'],
  },
  {
    slug: 'google-ads', pillar: 'Grow', name: 'Google Ads', title: 'Google Ads Management Company in Ahmedabad',
    description: 'Google Ads management for Ahmedabad businesses. Plan PPC search campaigns, audit existing ads, track conversions and optimize budgets with InfronixWeb.',
    heading: 'Google Ads Management Company in Ahmedabad',
    intro: 'Google Search campaigns can connect a clear offer with people already looking for it. We align keywords, ad copy and landing pages so the click leads to a useful next step.',
    includes: ['Demand and keyword research, including negative keywords', 'Campaign structure, ad groups and search ad copy', 'Location targeting and budget planning', 'Landing-page alignment and conversion tracking checks', 'Search-term review, testing and budget monitoring', 'Reporting on spend, enquiries and lead quality'],
    problems: 'Broad targeting and untracked forms can spend money without showing which enquiries are relevant. We check measurement and intent before expanding campaigns.',
    fit: 'Suitable for businesses with an identifiable search market, a clear offer, a working landing page and capacity to respond to enquiries.',
    process: ['Review demand, account access, goals and an affordable test budget.', 'Build tightly related ad groups and align the destination pages.', 'Validate conversion events and launch the agreed campaigns.', 'Review search terms, costs and sales feedback; test changes deliberately.'],
    example: 'Illustrative campaign: a local B2B service could target specific service searches within its service area and send visitors to a page with relevant examples and a short enquiry form.',
    measure: 'Track spend, click-through rate, cost per enquiry and qualified lead rate. Clicks are not sales; results depend on competition, offer, landing page and follow-up.',
    faqs: [['What does Google Ads management include?', 'The agreed scope can include an account audit, keyword and negative-keyword research, search campaign setup, ad copy, conversion tracking checks, optimization and reporting. Landing-page development and media spend are scoped separately.'], ['How much should a business spend on Google Ads?', 'We review search demand, likely click costs, your service area and the value of a qualified enquiry before proposing a test budget. Media spend is separate from management fees; there is no suitable fixed budget for every business.'], ['Do you manage existing Google Ads campaigns?', 'Yes, with appropriate account access. We review campaign history, search terms, budgets, targeting and tracking before recommending changes. Google AdWords is the former name of Google Ads, so older accounts can be reviewed too.'], ['How do you track Google Ads conversions?', 'We agree which actions matter, such as a completed enquiry or purchase, then check the relevant Google Ads or analytics events. A button click is reported separately from a confirmed lead, and offline sales feedback is included when reliable data is available.'], ['How long does it take to optimize a campaign?', 'Setup and tracking checks come first. Optimization continues as search terms, conversions and sales feedback accumulate. The review schedule depends on traffic and budget; we do not promise a fixed date for profitable results.'], ['Do you guarantee leads?', 'No. We define the measurement plan and review results, but cannot guarantee enquiries, sales or acquisition costs.']],
    related: ['seo', 'meta-ads', 'performance-marketing', 'web-development'],
  },
  {
    slug: 'meta-ads', pillar: 'Grow', name: 'Meta Ads', title: 'Meta Ads Management in Ahmedabad',
    description: 'Facebook and Instagram ad strategy, audience planning, creative testing, lead campaigns and conversion reporting for businesses in Ahmedabad.',
    heading: 'Introduce your offer to the right Facebook and Instagram audiences.',
    intro: 'Meta campaigns pair audience understanding with creative that gives people a reason to respond. We plan the offer, destination and follow-up alongside the ads.',
    includes: ['Facebook and Instagram campaign setup', 'Audience research and targeting plans', 'Creative briefs, ad copy and testing plans', 'Lead forms, website enquiry and remarketing campaigns', 'Conversion measurement and lead-source tracking', 'Budget review, performance reporting and iteration'],
    problems: 'A low cost per form submission can hide poor lead quality. We review the questions, creative message and sales outcomes together to understand which responses matter.',
    fit: 'Suitable for businesses with a clear audience, suitable visual assets and a process for contacting leads. Account and campaign eligibility must be checked first.',
    process: ['Review your offer, customer profile, assets and account permissions.', 'Plan creative variations, campaign objectives and the lead destination.', 'Check tracking and follow-up before starting the campaign.', 'Compare creative and audience performance using qualified responses.'],
    example: 'Illustrative campaign: a service business could test two creative approaches, ask relevant qualifying questions and route responses to a salesperson with their source attached.',
    measure: 'Review reach, click-through rate, cost per lead and qualified lead rate. Remarketing depends on available audiences, consent and platform requirements.',
    faqs: [['Do we need video?', 'Not for every campaign. Creative format depends on the message, placement and assets available; static and video approaches can be tested.'], ['Are cheap leads always better?', 'No. Lead quality, response rates and eventual customer acquisition matter more than the form-submission cost alone.'], ['Who owns the ad account?', 'Campaign work should use your business account with agreed partner access, keeping ownership and billing clear.']],
    related: ['digital-marketing/social-media-marketing', 'google-ads', 'performance-marketing', 'crm-automation'],
  },
  {
    slug: 'performance-marketing', pillar: 'Grow', name: 'Performance Marketing', title: 'Performance Marketing Agency in Ahmedabad',
    description: 'Connect advertising, landing pages and lead quality with measurable performance marketing. Review CPL, CPA, conversion rate and ROAS where revenue data is reliable.',
    heading: 'Make marketing decisions from the outcomes that matter.',
    intro: 'Performance marketing connects campaign spend to measurable actions. We help define those actions, improve the journey after the click and interpret results with the sales context included.',
    includes: ['Measurement plan and conversion definitions', 'Google and Meta campaign coordination', 'Landing-page and form conversion review', 'Creative and audience experiments', 'CRM feedback on qualified leads and customers', 'Reporting on acquisition costs and revenue where available'],
    problems: 'Separate channel reports can count the same conversion more than once or optimize for leads that never become customers. Shared definitions make the numbers more actionable.',
    fit: 'Suitable for businesses already investing in acquisition or ready to test a measurable funnel, with enough reliable data to evaluate outcomes.',
    process: ['Agree business goals, conversion definitions and data sources.', 'Audit campaign tracking and the landing-page journey.', 'Prioritize a small set of hypotheses and controlled tests.', 'Review acquisition costs alongside quality and sales outcomes.'],
    example: 'Illustrative review: a campaign with higher CPL may still be preferable if a greater share of its enquiries become suitable customers. Compare both stages before reallocating budget.',
    measure: 'CPL is spend divided by leads; CPA is spend divided by the agreed acquisition action. Conversion rate measures actions against eligible visits or clicks. CTR describes ad clicks, while ROAS compares attributed revenue with ad spend and is useful only when revenue tracking is reliable.',
    faqs: [['Can you guarantee ROI?', 'No. Margins, competition, customer demand, tracking quality and sales follow-up all affect outcomes.'], ['Do we need a CRM?', 'A CRM helps connect leads to sales, but a reliable agreed feedback process can be a starting point.'], ['How is this different from managing ads?', 'The scope includes the full journey from campaign to landing page and qualified outcome, rather than reporting on platform clicks alone.']],
    related: ['google-ads', 'meta-ads', 'web-development', 'crm-automation'],
  },
  {
    slug: 'ai-chatbot', pillar: 'Automate', name: 'AI Chatbots', title: 'AI Chatbot Development in Ahmedabad',
    description: 'Business chatbots grounded in approved content, with lead capture, human handoff and practical testing. Explore customer-support and enquiry-assistance use cases.',
    heading: 'Help customers get answers, with a clear path to your team.',
    intro: 'A business chatbot should answer from approved information and recognize when it needs help. We scope assistants for common questions, guided enquiries and support triage.',
    includes: ['Knowledge-source review and conversation planning', 'Answers grounded in approved business content', 'Lead capture and qualification questions', 'Human handoff and fallback responses', 'Integration with supported website or business tools', 'Evaluation, feedback review and content-update guidance'],
    problems: 'Repeated questions can delay responses, while an uncontrolled chatbot can give inaccurate answers. Defined boundaries and human escalation are part of the design.',
    fit: 'Suitable for businesses with recurring questions, maintained service information and staff available for exceptions. Sensitive or consequential decisions need human review.',
    process: ['Identify questions, approved sources and tasks the assistant must decline.', 'Design conversations, escalation and required integrations.', 'Test realistic questions, missing information and incorrect assumptions.', 'Pilot with monitoring and agree who maintains the knowledge sources.'],
    example: 'Illustrative assistant: a website visitor asks about service scope, receives an answer from approved pages and can choose to share project details with the team.',
    measure: 'Review answer accuracy, useful resolutions, handoff quality and unanswered questions. AI can make mistakes; model, hosting and integration costs depend on usage.',
    faqs: [['Will it make up answers?', 'AI can produce incorrect answers. Grounding, testing, fallback rules and monitoring reduce risk but do not eliminate it.'], ['Can customers reach a person?', 'A clear handoff route is defined during discovery, such as a support request or enquiry form.'], ['Can it use our documents?', 'Only with appropriate permission and after reviewing format, quality, sensitivity and update responsibility.']],
    related: ['ai-automation', 'whatsapp-automation', 'crm-automation'],
  },
  {
    slug: 'whatsapp-automation', pillar: 'Automate', name: 'WhatsApp Automation', title: 'WhatsApp Automation Services in Ahmedabad',
    description: 'Plan WhatsApp enquiry workflows, lead routing, appointment reminders and human handoff using supported business integrations and permission-based messaging.',
    heading: 'Keep WhatsApp enquiries organized and follow-ups timely.',
    intro: 'Connect incoming conversations to a useful next step. We plan enquiry routing, reminders and supported integrations around how your team already serves customers.',
    includes: ['Enquiry acknowledgement and routing workflows', 'Lead capture and CRM connections', 'Appointment and service reminder planning', 'Approved message-template workflows where required', 'Human handoff, opt-out handling and failure alerts', 'Integration testing and team documentation'],
    problems: 'Enquiries spread across chats can be missed or copied manually. A structured workflow records context and assigns responsibility without treating every customer conversation as a broadcast.',
    fit: 'Suitable for businesses using WhatsApp for opted-in customer communication and able to meet current platform and provider requirements.',
    process: ['Map conversations, consent records and staff responsibilities.', 'Check business setup, supported connections, provider charges and permissions.', 'Build routing and message flows with review and opt-out steps.', 'Test delivery failures, duplicate events and human escalation before rollout.'],
    example: 'Illustrative workflow: a customer requests an appointment, receives the agreed confirmation and has their details recorded in the CRM for a staff member to follow up.',
    measure: 'Track response time, successful handoffs, missed enquiries and delivery failures. Eligibility, template approval, permitted messaging and charges depend on the current platform and provider rules.',
    faqs: [['Can we message purchased contact lists?', 'The scope is permission-based customer communication, not unsolicited bulk messaging. Consent and platform requirements are reviewed first.'], ['Does it work with any WhatsApp account?', 'We first check the account, business setup and supported integration options. Feasibility is not assumed.'], ['Are provider fees included?', 'Platform and provider usage costs are identified separately from implementation and support in the proposal.']],
    related: ['ai-automation', 'ai-chatbot', 'crm-automation'],
  },
  {
    slug: 'crm-automation', pillar: 'Automate', name: 'CRM Automation', title: 'CRM Automation Services in Ahmedabad',
    description: 'Connect lead capture, assignment, sales follow-ups and CRM reporting. InfronixWeb scopes workflows around supported connections, data quality and your sales process.',
    heading: 'Give every enquiry a clear owner and next step.',
    intro: 'A CRM is more useful when the right information reaches it consistently. We connect lead sources, define assignment rules and reduce repetitive updates across your sales workflow.',
    includes: ['Website and campaign lead-source connections', 'Match customer details, check for missing information and avoid duplicate records', 'Lead assignment and qualification rules', 'Follow-up tasks, reminders and supported email workflows', 'Sales progress updates and reporting', 'Exception alerts, audit visibility and handover guidance'],
    problems: 'Manual copying, duplicate records and unclear ownership cause missed follow-ups. We agree the sales process before automating it so the system supports the team.',
    fit: 'Suitable for teams with a clear sales process and a CRM that offers the connections your sales process needs. Inconsistent data may need cleanup before rollout.',
    process: ['Agree where enquiries come from, which details are needed and who follows up at each sales stage.', 'Check permissions, connection limits and data quality with your CRM administrator.', 'Build a pilot that handles retries and duplicate enquiries safely.', 'Test exceptions with the sales team and document ongoing responsibility.'],
    example: 'Illustrative workflow: a form submission creates or updates a lead, records its service interest, assigns an owner and creates a follow-up task without duplicating an existing contact.',
    measure: 'Monitor assignment time, overdue tasks, duplicate rates and completeness of source data. Automation cannot fix an undefined process or guarantee that leads become customers.',
    faqs: [['Must we replace our CRM?', 'Usually the first step is to assess your current system. Replacement is considered only if a required workflow cannot be supported reliably.'], ['How are duplicate leads handled?', 'We agree matching rules and test updates, retries and conflicts before enabling the connection.'], ['Can it connect ads and website forms?', 'Where the source and CRM provide supported access, we can scope those connections and preserve source information for reporting.']],
    related: ['ai-automation', 'whatsapp-automation', 'performance-marketing'],
  },
  {
    slug: 'digital-marketing/social-media-marketing', pillar: 'Grow', name: 'Social Media Marketing', title: 'Social Media Marketing in Ahmedabad',
    description: 'Instagram, Facebook and LinkedIn content strategy and management for Ahmedabad businesses. Plan posts, reels, content calendars and meaningful reporting.',
    related: ['meta-ads', 'digital-marketing', 'web-development'],
  },
  {
    slug: 'digital-marketing/paid-advertising', pillar: 'Grow', name: 'Paid Advertising', title: 'Paid Advertising Services in Ahmedabad',
    description: 'Explore Google Ads and Meta Ads for your business. Compare channels, landing-page needs, tracking and campaign management with InfronixWeb in Ahmedabad.',
    related: ['google-ads', 'meta-ads', 'performance-marketing'],
  },
];
export const getService = (slug) => services.find(service => service.slug === slug);
export const newServiceSlugs = ['google-ads', 'meta-ads', 'performance-marketing', 'ai-chatbot', 'whatsapp-automation', 'crm-automation'];
